*MAT_USER_DEFINED_MATERIAL_MODELS_TITLE
isotropic plasticity from Seupel.AEF.2018 with damage
$#     mid        ro        mt       lmc       nhv    iortho     ibulk        ig
       2447.85000E-9        44        40        33         0         1         2
$#   ivect     ifail    itherm    ihyper      ieos      lmca    unused    unused
         0         0         1         1         0        24                    
$#      p1        p2        p3        p4        p5        p6        p7        p8
$  bulkMod  shearMod                                        hsv-versio cm-versio
    175000 80769.231         0         0         0         0         2         0
$#      p1        p2        p3        p4        p5        p6        p7        p8
$  hardiso yieldStre   hardMod yieldIncr   saturat       exp    linExp loadCurve
         3  391.183    677.777   217.928  47.0388         0          0         0
$#      p1        p2        p3        p4        p5        p6        p7        p8
         0         0         0         0         0         0         0         0
$#      p1        p2        p3        p4        p5        p6        p7        p8
         0         0         0         0         0         0         0         0
$#      p1        p2        p3        p4        p5        p6        p7        p8
$ dmg_type  dmg_coup  penParam nloc_type   dmg_fnc      h_TC
         7         1         1         6         3         0         0         0
$ LMCA
$#      p1        p2        p3        p4        p5        p6        p7        p8
         0         0         0         0         0         0         0         0
$#      p1        p2        p3        p4        p5        p6        p7        p8
         0         0         0         0         0         0         0         0
$#      p1        p2        p3        p4        p5        p6        p7        p8
$        -         - alphaFail     eta_4   alpha_c   dmg_exp
         0         0    0.4            1      0.01         2         0         0
$        -         -    D_crit     eta_4alpha_fail
$         0         0      0.99         1       0.4         0         0         0
*MAT_THERMAL_USER_DEFINED
$#    tmid        ro        mt       lmc       nhv      aopt    iortho      ihve
         1       0.0        11         8         1       0.0         0         1
$#      p1        p2        p3        p4        p5        p6        p7        p8
         1       0.0       0.0       0.0       0.0       0.0       0.0       0.0
